In [1]:

import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:

housing_data_df = pd.read_csv('data/kc_house_data.csv')
housing_data_df.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [3]:

size_log = np.log(np.array(housing_data_df['sqft_lot']))
bedrooms = np.array(housing_data_df['bedrooms'])
target_col = housing_data_df.price.to_numpy()

In [4]:

def linear_regression(params, feature1=size_log, feature2=bedrooms):
    return params[0] + feature1*params[1] + feature2*params[2]

In [5]:

def loss_function(params, targets=target_col, feature1=size_log, feature2=bedrooms):
    predictions = linear_regression(params, feature1, feature2)
    return tf.losses.mae(targets, predictions)

In [6]:

def print_results(params):
    return print('loss: {:0.3f}, intercept: {:0.3f}, slope_1: {:0.3f}, slope_2: {:0.3f}'.format \
                 (loss_function(params).numpy(), params[0].numpy(), params[1].numpy(), params[2].numpy()))

In [7]:

def optimisation(params, num_opt=100, opt=tf.optimizers.Adam(0.9)):

    for i in range(num_opt):
        # minimise loss
        opt.minimize(lambda: loss_function(params), var_list=[params])
        print_results(params)

In [8]:

if __name__ == '__main__':
    # initial slope and intercept
    params = tf.Variable([0.1, 0.05, 0.02])
    
    # perform linear regression
    linreg = optimisation(params)

loss: 540075.500, intercept: 1.000, slope_1: 0.950, slope_2: 0.920
loss: 540063.250, intercept: 1.900, slope_1: 1.850, slope_2: 1.820
loss: 540051.562, intercept: 2.800, slope_1: 2.750, slope_2: 2.720
loss: 540039.375, intercept: 3.700, slope_1: 3.650, slope_2: 3.620
loss: 540027.438, intercept: 4.600, slope_1: 4.550, slope_2: 4.520
loss: 540015.438, intercept: 5.500, slope_1: 5.450, slope_2: 5.420
loss: 540003.312, intercept: 6.400, slope_1: 6.350, slope_2: 6.320
loss: 539991.375, intercept: 7.300, slope_1: 7.250, slope_2: 7.220
loss: 539979.250, intercept: 8.200, slope_1: 8.150, slope_2: 8.120
loss: 539967.312, intercept: 9.100, slope_1: 9.050, slope_2: 9.020
loss: 539955.188, intercept: 10.000, slope_1: 9.950, slope_2: 9.920
loss: 539943.188, intercept: 10.900, slope_1: 10.850, slope_2: 10.820
loss: 539931.188, intercept: 11.800, slope_1: 11.750, slope_2: 11.720
loss: 539919.250, intercept: 12.700, slope_1: 12.650, slope_2: 12.620
loss: 539907.125, intercept: 13.600, slope_1: 13.550, slope_2: 13.520
loss: 539895.125, intercept: 14.500, slope_1: 14.450, slope_2: 14.420
loss: 539883.125, intercept: 15.400, slope_1: 15.350, slope_2: 15.320
loss: 539871.125, intercept: 16.300, slope_1: 16.250, slope_2: 16.220
loss: 539859.062, intercept: 17.200, slope_1: 17.150, slope_2: 17.120
loss: 539847.125, intercept: 18.100, slope_1: 18.050, slope_2: 18.020
loss: 539835.000, intercept: 19.000, slope_1: 18.950, slope_2: 18.920
loss: 539823.000, intercept: 19.900, slope_1: 19.850, slope_2: 19.820
loss: 539810.938, intercept: 20.800, slope_1: 20.750, slope_2: 20.720
loss: 539798.875, intercept: 21.700, slope_1: 21.650, slope_2: 21.620
loss: 539786.938, intercept: 22.600, slope_1: 22.550, slope_2: 22.520
loss: 539774.812, intercept: 23.500, slope_1: 23.450, slope_2: 23.420
loss: 539762.875, intercept: 24.400, slope_1: 24.350, slope_2: 24.320
loss: 539750.875, intercept: 25.300, slope_1: 25.250, slope_2: 25.220
loss: 539738.750, intercept: 26.200, slope_1: 26.150, slope_2: 26.120
loss: 539726.812, intercept: 27.100, slope_1: 27.050, slope_2: 27.020
loss: 539714.750, intercept: 28.000, slope_1: 27.950, slope_2: 27.920
loss: 539702.812, intercept: 28.900, slope_1: 28.850, slope_2: 28.820
loss: 539690.688, intercept: 29.800, slope_1: 29.750, slope_2: 29.720
loss: 539678.750, intercept: 30.700, slope_1: 30.650, slope_2: 30.620
loss: 539666.688, intercept: 31.600, slope_1: 31.550, slope_2: 31.520
loss: 539654.750, intercept: 32.500, slope_1: 32.450, slope_2: 32.420
loss: 539642.625, intercept: 33.400, slope_1: 33.350, slope_2: 33.320
loss: 539630.562, intercept: 34.300, slope_1: 34.250, slope_2: 34.220
loss: 539618.562, intercept: 35.200, slope_1: 35.150, slope_2: 35.120
loss: 539606.562, intercept: 36.100, slope_1: 36.050, slope_2: 36.020
loss: 539594.500, intercept: 37.000, slope_1: 36.950, slope_2: 36.920
loss: 539582.562, intercept: 37.900, slope_1: 37.850, slope_2: 37.820
loss: 539570.438, intercept: 38.800, slope_1: 38.750, slope_2: 38.720
loss: 539558.438, intercept: 39.700, slope_1: 39.650, slope_2: 39.620
loss: 539546.438, intercept: 40.600, slope_1: 40.550, slope_2: 40.520
loss: 539534.312, intercept: 41.500, slope_1: 41.450, slope_2: 41.420
loss: 539522.375, intercept: 42.400, slope_1: 42.350, slope_2: 42.320
loss: 539510.375, intercept: 43.300, slope_1: 43.250, slope_2: 43.220
loss: 539498.250, intercept: 44.200, slope_1: 44.150, slope_2: 44.120
loss: 539486.250, intercept: 45.100, slope_1: 45.050, slope_2: 45.020
loss: 539474.250, intercept: 46.000, slope_1: 45.950, slope_2: 45.920
loss: 539462.250, intercept: 46.900, slope_1: 46.850, slope_2: 46.820
loss: 539450.188, intercept: 47.800, slope_1: 47.750, slope_2: 47.720
loss: 539438.188, intercept: 48.700, slope_1: 48.650, slope_2: 48.620
loss: 539426.250, intercept: 49.600, slope_1: 49.550, slope_2: 49.520
loss: 539414.062, intercept: 50.500, slope_1: 50.450, slope_2: 50.420
loss: 539402.125, intercept: 51.400, slope_1: 51.350, slope_2: 51.320
loss: 539390.125, intercept: 52.300, slope_1: 52.250, slope_2: 52.220
loss: 539378.062, intercept: 53.200, slope_1: 53.150, slope_2: 53.120
loss: 539366.062, intercept: 54.100, slope_1: 54.050, slope_2: 54.020
loss: 539354.000, intercept: 55.000, slope_1: 54.950, slope_2: 54.920
loss: 539342.000, intercept: 55.900, slope_1: 55.850, slope_2: 55.820
loss: 539329.875, intercept: 56.800, slope_1: 56.750, slope_2: 56.720
loss: 539318.000, intercept: 57.700, slope_1: 57.650, slope_2: 57.620
loss: 539306.000, intercept: 58.600, slope_1: 58.550, slope_2: 58.520
loss: 539293.875, intercept: 59.500, slope_1: 59.450, slope_2: 59.420
loss: 539281.875, intercept: 60.400, slope_1: 60.350, slope_2: 60.320
loss: 539269.875, intercept: 61.300, slope_1: 61.250, slope_2: 61.220
loss: 539257.812, intercept: 62.200, slope_1: 62.150, slope_2: 62.120
loss: 539245.875, intercept: 63.100, slope_1: 63.050, slope_2: 63.020
loss: 539233.812, intercept: 64.000, slope_1: 63.950, slope_2: 63.920
loss: 539221.625, intercept: 64.900, slope_1: 64.850, slope_2: 64.820
loss: 539209.812, intercept: 65.800, slope_1: 65.750, slope_2: 65.720
loss: 539197.688, intercept: 66.700, slope_1: 66.650, slope_2: 66.620
loss: 539185.625, intercept: 67.600, slope_1: 67.550, slope_2: 67.520
loss: 539173.688, intercept: 68.500, slope_1: 68.450, slope_2: 68.420
loss: 539161.625, intercept: 69.400, slope_1: 69.350, slope_2: 69.320
loss: 539149.625, intercept: 70.300, slope_1: 70.250, slope_2: 70.220
loss: 539137.562, intercept: 71.200, slope_1: 71.150, slope_2: 71.120
loss: 539125.500, intercept: 72.100, slope_1: 72.050, slope_2: 72.020
loss: 539113.500, intercept: 73.000, slope_1: 72.950, slope_2: 72.920
loss: 539101.562, intercept: 73.900, slope_1: 73.850, slope_2: 73.820
loss: 539089.438, intercept: 74.800, slope_1: 74.750, slope_2: 74.720
loss: 539077.438, intercept: 75.700, slope_1: 75.650, slope_2: 75.620
loss: 539065.500, intercept: 76.600, slope_1: 76.550, slope_2: 76.520
loss: 539053.375, intercept: 77.500, slope_1: 77.450, slope_2: 77.420
loss: 539041.438, intercept: 78.400, slope_1: 78.350, slope_2: 78.320
loss: 539029.375, intercept: 79.300, slope_1: 79.250, slope_2: 79.220
loss: 539017.188, intercept: 80.200, slope_1: 80.150, slope_2: 80.120
loss: 539005.375, intercept: 81.100, slope_1: 81.050, slope_2: 81.020
loss: 538993.250, intercept: 82.000, slope_1: 81.950, slope_2: 81.920
loss: 538981.250, intercept: 82.900, slope_1: 82.850, slope_2: 82.820
loss: 538969.312, intercept: 83.800, slope_1: 83.750, slope_2: 83.720
loss: 538957.062, intercept: 84.700, slope_1: 84.650, slope_2: 84.620
loss: 538945.125, intercept: 85.600, slope_1: 85.550, slope_2: 85.520
loss: 538933.188, intercept: 86.500, slope_1: 86.450, slope_2: 86.420
loss: 538921.188, intercept: 87.400, slope_1: 87.350, slope_2: 87.320
loss: 538909.062, intercept: 88.300, slope_1: 88.250, slope_2: 88.220
loss: 538897.062, intercept: 89.200, slope_1: 89.150, slope_2: 89.120
loss: 538885.125, intercept: 90.100, slope_1: 90.050, slope_2: 90.020